//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmprestimoJogos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Emprestimo
    {
        [Key]
        public int IdEmprestimo { get; set; }

        [Display(Name = "Amigo")]
        [Required(ErrorMessage = "Um amigo deve ser selecionado.")]
        public int IdAmigo { get; set; }

        [Display(Name = "Jogo")]
        [Required(ErrorMessage = "Um jogo deve ser selecionado.")]
        public int IdJogo { get; set; }

        [Display(Name = "Data de Empréstimo")]
        [Required(ErrorMessage = "A data do empréstimo deve ser informado.")]
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime DataEmprestimo { get; set; }
    
        public virtual Amigo Amigo { get; set; }
        public virtual Jogo Jogo { get; set; }
    }
}
